# Generated by Django 4.2.3 on 2023-07-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('vul_critica', models.CharField(max_length=2)),
                ('vul_alta', models.CharField(max_length=2)),
                ('vul_media', models.CharField(max_length=2)),
                ('vul_baixa', models.CharField(max_length=2)),
                ('scan_date', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
